### ISSUE TITLE
ValueError: x and y should have a same length  - When trying to generate a Graphic EQ using guipeace.exe

### ISSUE THREAD

**Issue by rigopoui** [zettonaender/eqapotographiceq-gui#5]
Console output:
```
Galaxy Buds2 Pro Stereo Headphones {a4d136e5-f3a1-4d41-8878-07571e01ce18}; Bench
mark
Invalid channel position L
Invalid channel position SL
Invalid channel position R
Invalid channel position SR
Invalid channel position L
Invalid channel position R
Invalid channel position RL
Invalid channel position RR
Invalid channel position SL
Invalid channel position SUB
Invalid channel position RL
Invalid channel position RR
Invalid channel position SR
Invalid channel position L
Invalid channel position RL
Invalid channel position SL
Invalid channel position R
Invalid channel position RR
Invalid channel position SR
Press any key to continue . . .
Benchmark 1.3
Run "C:/Program Files/EqualizerAPO/Benchmark.exe -h" to show usage info

Reading sound data from dirac24_48_mono.wav
Reading input file took 0.0002076 seconds

Loading configuration took 30.5998 ms

Processing 24000 frames from 1 channel(s)
24000 samples processed in 0.021554 seconds
This is equivalent to 4.31% CPU load (one core) when processing in real time
Max output level: 0.000000 (-inf dB)

Writing output to C:/Users/rigopoui/Desktop/guipeace/ssweep.wav

"C:/Program Files/EqualizerAPO/Benchmark.exe" -i dirac24_48_mono.wav -o "C:/User
s/rigopoui/Desktop/guipeace/ssweep.wav"
C:\Users\rigopoui\Desktop\guipeace\ok.py:32: RuntimeWarning: divide by zero enco
untered in log10
  arr=20*np.log10(abs(arr))

Traceback (most recent call last):
  File "eqapotographiceq-gui\guipeace.py", line 144, in <module>
  File "C:\Users\rigopoui\Desktop\guipeace\ok.py", line 55, in startyourengine
    doeq()
  File "C:\Users\rigopoui\Desktop\guipeace\ok.py", line 24, in doeq
    batch_processing(input_dir="ssweep",output_dir=rp('myresult/ssweep'),standar
dize_input=True,compensation='zero.csv',equalize=True,show_plot=showplot)
  File "C:\Users\rigopoui\Desktop\guipeace\autoeq.py", line 79, in batch_process
ing
    fr.center()
  File "C:\Users\rigopoui\Desktop\guipeace\frequency_response.py", line 978, in
center
    interpolator = InterpolatedUnivariateSpline(np.log10(equal_energy_fr.frequen
cy), equal_energy_fr.raw, k=1)
  File "scipy\interpolate\_fitpack2.py", line 661, in __init__
  File "scipy\interpolate\_fitpack2.py", line 229, in validate_input
ValueError: x and y should have a same length
[14772] Failed to execute script 'guipeace' due to unhandled exception!
```

Any idea why this happens? IIRC I have used this tool successfully in the past.

**Comment by zettonaender** [comment]
Sorry for the late reply, it seems that peace.txt contains a command for channel selection (**Channel: L** and such). Can you try removing these lines and run the program again?
