### ISSUE TITLE
error when clicking ok to generate

### ISSUE THREAD

**Issue by RAFAELCARA** [zettonaender/eqapotographiceq-gui#7]
![image](https://user-images.githubusercontent.com/46977733/221416387-d8641a70-650e-415a-b473-400d9c047114.png)

![image](https://user-images.githubusercontent.com/46977733/221416484-bdbe68d4-608a-4b12-a3c5-b095e983e5a5.png)

(I'm using the modified benchmark.exe)

all
Traceback (most recent call last):
  File "eqapotographiceq-gui-forexe\guipeace.py", line 131, in <module>
  File "eqapotographiceq-gui-forexe\guipeace.py", line 29, in bench
  File "subprocess.py", line 503, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
[10548] Failed to execute script 'guipeace' due to unhandled exception!

**Comment by lonelyghosts** [comment]
I am getting the same 'WinError 216' as well.

**Comment by nitinyogi950-prog** [comment]
Many give my amount to pay me
